### PR TITLE
fix scrollbars showing on some setups

### LINKED ISSUE #97: Scroll bars randomly showing in provider popup
- observed on Mac + Chrome
- 
Image

### PR DESCRIPTION
**Pull request by rohenaz**

### CODE REVIEW

**Comment by danwag06** [comment]
@rohenaz I think we want the local dev env to display the same dimensions as how it will display when the chrome popout or popup windows show to avoid formatting/css issues (it was optimized for those specific hard coded dimensions.). Attached is what the local env looks like and what the popout window looks like on my machine with the changes. To see the popout you'll need to run `npm run build` and upload the build file into chrome://extensions dev mode

Screen Shot 2023-11-04 at 8 41 48 AM
d4c-41b6-8b90-8aac0060f0e5">

**Comment by danwag06** [comment]
<img width="1727" alt="Screen Shot 2023-11-04 at 8 37 38 AM" src="https://github.com/Panda-Wallet/panda-wallet/assets/25462225/b3f4140a-d

**Comment by danwag06** [comment]
Screen Shot 2023-11-04 at 8 37 38 AM

**Comment by rohenaz** [comment]
ok i think we can add the hard coded sizes (or something slightly lower to now cause a scroll) as a min-width / min-height. I'll look into that...

**Review by danwag06 — APPROVED** [review]

**Pull request merged**
