### PR TITLE
Update signMessage to support base64 and hex encodings

### LINKED ISSUE #61: signMessage doesn't accept a Buffer, which is needed for SIGMA/AIP

### PR DESCRIPTION
**Pull request by shruggr**

### CODE REVIEW

**Comment by danwag06** [comment]
@shruggr is this ready or nah?

**Comment by shruggr** [comment]
Nope. I haven't tested it yet.

**Comment by shruggr** [comment]
@danwag06 I think I have some problems with my wiring still. I'm getting the following: 
```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
Uncaught Error: Extension context invalidated.
```

**Comment by shruggr** [comment]
Screenshot 2023-10-27 at 2 24 11 PM

**Comment by danwag06** [comment]
@shruggr if you reload a new build you'll have to refresh the page you are trying to call from

**Comment by danwag06** [comment]
@shruggr let me know when this is ready for review.

**Comment by shruggr** [comment]
@danwag06 I have this 95% of the way there, but the new `encoding` property does not appear to be making in from the function call on the web page. I think I might need a little wiring help. I have verified that this works properly with the default `utf8` encoding

**Comment by shruggr** [comment]
Associated provider PR: https://github.com/Panda-Wallet/panda-wallet-provider/pull/2

**Comment by danwag06** [comment]
@shruggr I was able to test this and it seems good to go. Gonna merge.

**Review by danwag06 — APPROVED** [review]

**Pull request merged**
