### PR TITLE
Fix #81

### LINKED ISSUE #81: `wallet.getOrdinals()` returns empty array
The result of the `getOrdinals` function returns an empty array, even though my wallet contains multiple, which also show up correctly in the extension.

I've only tried in testnet mode. I didn't try mainnet.

### PR DESCRIPTION
**Pull request by zhfnjust**

### CODE REVIEW

**Comment by danwag06** [comment]
@zhfnjust is this different than what was already merged in #105?

**Comment by danwag06** [comment]
I did some testing here and the provider feels broken. I was unable to test calling getOrdinals because it would not allow me to connect.

**Comment by zhfnjust** [comment]
the master branch has the same connect issue, it was not cause by mine PR, i am looking at it

**Comment by zhfnjust** [comment]
sorry , it was mine issue. and fixed.

**Comment by zhfnjust** [comment]
> @zhfnjust is this different than what was already merged in #105?

yes , this is a supplement

**Comment by zhfnjust** [comment]
There is indeed something wrong with the master branch, I'm still fixing it

**Comment by zhfnjust** [comment]
now fixed

**Review by danwag06 — CHANGES_REQUESTED** [review]
@zhfnjust Please merge main as I fixed a couple of bugs I noticed while reviewing this that currently exist in production. I don't think it should cause any conflicts.

Everything seems to work as expected accept for the pop up window persisting after requests have resolved. The UX we want is that an app invokes the provider, and the popup window appears for the users approval. If they approve the request, and the operations finish, the window should be removed, otherwise it creates and additional step of the user needing to close the window. 

**Note: Please allow for any success snackbar messages to timeout before auto closing the windows (where applicable). This should be tested for all requests that invoke a popup:**

- connect
- sendBsv
- transferOrdinal
- purchaseOrdinal
- broadcastRawTx
- signMessage
- getSignatures

**Comment by zhfnjust** [comment]
I don’t understand what else needs to be done with this PR, testing?

**Comment by danwag06** [comment]
> I don’t understand what else needs to be done with this PR, testing?

In main, if you call the provider, after the user agrees, and the operation processes, the popup window will automatically close after the snackbar success message times out.

In this pr, the popup window does not auto dismiss for the listed methods above (which means the user needs to close out the popup window manually. Need to think of it from the developer/app perspective. Once an action is complete there is no need to keep the wallet (pop up window) open.

**Comment by zhfnjust** [comment]
@danwag06 can you check this again

**Review by danwag06 — APPROVED** [review]
Fantastic work. Everything working perfectly!

**Pull request merged**
