### PR TITLE
add feature `getSignatures` to support signing arbitrary smart contract txs.

### PR DESCRIPTION
**Pull request by freedomhero**
`getSignatures` is added for signing arbitrary transaction inputs to support smart contract features.

Examples:

```ts
const sigRequests: SignatureRequest[] = [
  { 
    prevTxId: $txid_0,
    outputIndex: 0,
    inputIndex: 0,
    satoshis: 1,
    address: ordAddress,
  },
  { 
    prevTxId: $txId_1,
    outputIndex: 0,
    inputIndex: 1,
    satoshis: 1000,
    address: bsvAddress,
    scriptHex: $contract_locking_script_hex,
  }
]

const sigResponses: SignatureResponse[] = await wallet.getSignatures({
  txHex: $unsignedTxRawHex,
  sigRequests
})
```

Types:
```ts
/** 
 * `SignatureRequest` contains required informations for a signer to sign a certain input of a transaction.
 */
export interface SignatureRequest {
  prevTxId: string;
  outputIndex: number;
  /** The index of input to sign. */
  inputIndex: number;
  /** The previous output satoshis value of the input to spend. */
  satoshis: number;
  /** The address(es) of corresponding private key(s) required to sign the input. */
  address: string | string[];
  /** The previous output script of input, default value is a P2PKH locking script for the `address` if omitted. */
  scriptHex?: string;
  /** The sighash type, default value is `SIGHASH_ALL | SIGHASH_FORKID` if omitted. */
  sigHashType?: number;
  /** 
   * Index of the OP_CODESEPARATOR to split the previous output script at during verification.
   * If undefined, the whole script is used.
   * */
  csIdx?: number;
  /** The extra information for signing. */
  data?: unknown;
}

/** 
 * `SignatureResponse` contains the signing result corresponding to a `SignatureRequest`.
 */
export interface SignatureResponse {
  /** The index of input. */
  inputIndex: number;
  /** The signature.*/
  sig: string;
  /** The public key bound with the `sig`. */
  publicKey: string;
  /** The sighash type, default value is `SIGHASH_ALL | SIGHASH_FORKID` if omitted. */
  sigHashType: number;
  /** The index of the OP_CODESEPARATOR to split the previous output script at.*/
  csIdx?: number;
}
```

Default Popup Page:
image

Popup Page in Details:
image

### CODE REVIEW

**Comment by danwag06** [comment]
@xhliu and @shruggr I'm requesting some assistance in reviewing this one. Assuming it's good with you guys, I will handle testing the provider functionality and getting the docs updated to include this new method. I've done very little with the smart contract side of things so I'd feel more comfortable with your alls approval.

**Comment by freedomhero** [comment]
Actually, it can be considered an enhanced version of the feature  `SignTransaction` which has several advantages:

* It can get multiple signatures for many addresses or inputs in a single request for user to sign only once. 
* It has some more options to control the signatures, such as `csIdx`, for advanced scripts. (Although it’s not fully implemented yet in this commit.)

I think you can keep both or just use this one to replace the `SigTransaction` feature after the merge.

**Comment by shruggr** [comment]
This is a much better and fuller implementation than my `signTransaction` method. I can try and wire up the same test I used previously, but by design, this is better in every way.

**Comment by danwag06** [comment]
@shruggr if you could run that same test that would be awesome. Everything else looks good. Happy to merge once that's successfully tested. The plan will to use this instead of the old method as having both seems redundant given we're still in beta.

cc @freedomhero

**Comment by shruggr** [comment]
Looks good: https://ordinals.gorillapool.io/api/testing

**Review by danwag06 — APPROVED** [review]

**Pull request merged**
