### PR TITLE
update token UI

### PR DESCRIPTION
**Pull request by zhfnjust**
1. [update token UI](https://github.com/Panda-Wallet/panda-wallet/commit/42c0798433295192028c980c030ef0da8b1e558a)
2. [not show Processing infrequently](https://github.com/Panda-Wallet/panda-wallet/commit/569cdbcf3d08bd89b7e6c6f0c53ecb8dec2ba69d)
3. [remove cache TokenInfos](https://github.com/Panda-Wallet/panda-wallet/commit/d464f2bfc360e55fe2cac08a9ca99d6091368d6c)
4. add copy token ID

image
image

image

### CODE REVIEW

**Comment by zhfnjust** [comment]
@shruggr @danwag06

**Comment by danwag06** [comment]
@zhfnjust I will test this out once we get past this BSV20 lim 1 mint madness

**Review by danwag06 — CHANGES_REQUESTED** [review]
Can we reduce the space here a little? So the Icon and Sym aren't so far apart... maybe like 0.5rem or 1rem. It seems like the distances between token symbols and Icons are inconsistent depending on the length of the token amount. Ideally the  that space is consistent.

Screen Shot 2023-12-14 at 1 04 34 PM

**Comment by zhfnjust** [comment]
@danwag06 fixed

**Review by danwag06 — APPROVED** [review]

**Pull request merged**
