### PR TITLE
support Bsv20

### LINKED ISSUE #4: BSV20 Support

### PR DESCRIPTION
**Pull request by zhfnjust**
Add two major features, Fix #4

- [x] support show bsv20 token
- [x] support send bsv20 token

look below:

image

image

### CODE REVIEW

**Comment by zhfnjust** [comment]
It would be even better if add the following features:

- [ ] Transaction History
- [ ] receive notifications
- [ ] Token value display

**Comment by danwag06** [comment]
@zhfnjust I'm going to makes some tweaks to the design and tag team this PR with you. I'll also address the conflicts that have arose from the broadcast change we just made.

**Comment by shruggr** [comment]
I just tested with a number of transfers. It appears to work well in most scenarios, but has an issue with tokens which were previously transferred with `implied` transfers. Implied transfers are no longer valid for new transfers, but are supported for transfers before block 800000, or something like that.

With an implied transfer, there is no transfer inscription, so you can't parse the bsv20 from the inscription and you need to get the data from the indexer. There are currently 953 implied outpoints in existence across 82 different addresses. `implied: true` is returned in the TxoData for these txos.

For users with implied transfer outpoints, transfer of that ticker will likely break, as it did for me.

**Comment by danwag06** [comment]
Before making any additional changes (if required).... Let me get these merge conflicts handled first. Adding global orderbook ord listings and cancels along with this change and upgrading to use the GP endpoint created an undesirable amount of conflicts. I'm nearly through it though.

**Comment by danwag06** [comment]
Ok @zhfnjust I have these conflicts addressed. Here are our options:

1. Give me access to push to your remote bsv20 branch and I'll push the changes up
2. We merge the branch i created to fix the issues... https://github.com/Panda-Wallet/panda-wallet/compare/main...pr-65

Either way, I've tested everything and it it's working as expected.

**I would propose that we go ahead and get this merged since there are a lot of changes and then create separate issues for what @shruggr mentioned above and the design changes I want to make.**

**Comment by zhfnjust** [comment]
@danwag06 Invited

**Review by danwag06 — APPROVED** [review]
Nice work!

**Pull request merged**
