### PR TITLE
feat: #103 add optional keyTypes to signMessage method

### LINKED ISSUE #103: Add optional keyType to signMessage method

### PR DESCRIPTION
**Pull request by danwag06**

### CODE REVIEW

**Comment by danwag06** [comment]
@shruggr this was a request from @jadwahab FYI

**Comment by jadwahab** [comment]
@danwag06 I'd prefer to use separate keys to sign messages than the keys used to sign tx inputs (UTXOs) so that there's a clear distinction between the sign message API and the sign inputs API (get signatures). That's what Relay does with their `identity` key (which we're calling the `locking` key here.

**Comment by danwag06** [comment]
@jadwahab peep this

**Review by jadwahab — APPROVED** [review]
LGTM!

**Pull request merged**
